

# CASE :- CASE ARE USED TO DIVIDE DATA INTO ACCORDING TO CONDITION AND SHOW THE VALUE  ACCORDING TO USER

USE EMPLOYE_DB;

SELECT * FROM EMPLOYEES_;
 #1. WRITE A QUERY TO DIVIDE DATA INTO TWO CONDITIO WHERE AGE IS GREATER THAN 35 THEN PRINT SENIORS
 # IF AGE IS LESS THAN 35 THEN SHOW JUNIOR
 
 SELECT EMP_NAME,AGE,CASE 
 WHEN  AGE>35 THEN "SENIOR"
 ELSE "JUNIOR" END AS STATUS
 FROM EMPLOYEES_ ;
 
 # 2. WRITE A QUERY TO SHOW THE STATUS IF NAME STARTSWITH R THEN SHOW YES ELSE NO
 
 SELECT EMP_NAME
 ,CASE
 WHEN 
 LEFT(EMP_NAME,1)="R" THEN "YES"
 ELSE "NO" END AS STATUS
 FROM EMPLOYEES_;
 
 
 #3.  WRITE A QUERY TO SHOW THE STATUS IF AGE IS LESS THEN 30 AND SALARY IS LESS THEN 35K THEN SHOW  else B
 
 SELECT AGE,SALARY,CASE 
 WHEN AGE<30 AND SALARY<35000 THEN "A"
 ELSE "B" END AS STATUS FROM EMPLOYEES_;
 
 
 
 # 4. WRITE A QUERY TO SHOW THE BONUS OF EMP IF SALARY IS > THAN 30K THEN SHOW 20% OFSALARY ELSE 10% SALARY
 
 SELECT EMP_NAME,SALARY,CASE
 WHEN SALARY>30000 THEN ROUND(SALARY*20/100)
 ELSE ROUND(SALARY*10/100) END AS BONUS FROM EMPLOYEES_;
 
 
 
SELECT EMP_NAME,AGE,CASE 
WHEN AGE<30 THEN "A"
WHEN AGE<40 THEN "B"
WHEN AGE<50 THEN "C"
ELSE "D" END AS STATUS
FROM EMPLOYEES_ order by  STATUS DESC ;


#6. WRITE A QUERY TO SHOW IF NAME STARTS WITH R ,A AND T THEN PRINT YES ELSE PRINT NO

SELECT EMP_NAME , CASE
WHEN LEFT(EMP_NAME,1)="R"THEN "YES"
WHEN LEFT(EMP_NAME,1)="A" THEN "YES"
WHEN LEFT(EMP_NAME,1)="T" THEN "YES"
ELSE "NO" END AS STATUS 
FROM EMPLOYEES_;

#7. WRITE A QUERY TO SHOW 

SELECT AGE, DEPT,SALARY,CASE
WHEN DEPT='DATA ANALYST' AND AGE BETWEEN 30 AND 50 THEN "A"
WHEN DEPT= "DATA SCIENTIST"OR DEPT="MIS ANALYST" AND AGE BETWEEN 20 AND 30 THEN "B"
WHEN DEPT='DATA ENGINEER' AND SALARY BETWEEN 45000 AND 60000 THEN "C"
ELSE "D" END AS STATUS 
FROM EMPLOYEES_;


#...........................................................................................


# IF 
SELECT AGE,IF (AGE>30,"A","B") AS STATUS
FROM EMPLOYEES_;

SELECT AGE , IF(AGE<30,"A",IF(AGE<40,"B","C"))
AS STATUS FROM EMPLOYEES_;

use employe_db;
select * from employees_;


# write a query to show the status of employees whose age is greater then avg age show yes or show no

select AGE , CASE WHEN 
 AGE >(SELECT AVG(AGE) FROM EMPLOYEES_) THEN "YES" ELSE "NO" END AS STATUS FROM EMPLOYEES_;
 
 
 SELECT AVG(AGE) FROM EMPLOYEES_;

SELECT  EMP_NAME , SALARY , CASE WHEN 
SALARY<(SELECT AVG(SALARY) FROM EMPLOYEES_)   
AND LENGTH(TRIM(EMP_NAME))>14 THEN "A" ELSE "B"
END AS STATUS FROM EMPLOYEES_ 
 ;

# MASK THE CONTACT NO IN PATNA JAIPUR AND NOIDA

SELECT EMP_NAME,STATE,CASE WHEN
STATE IN ("PATNA","JAIPUR","NOIDA") THEN "XXXXXXXXXX"
ELSE`PHN` END AS MASK FROM EMPLOYEES_;

#.......................................LIKE...AND.....NOT LIKE..................................

# .................................SQL WILD CARD...........................
# STARTSWITH :- "A%"
# ENDSWITH  :- "%A"
# STARTSWITH AND ENDSWITH : "A%A"
# CONTAIN :- "%A%"
#LENGTH :- "___________________"



#SHOW THE NAME OF EMPLOYEE WHOSE NAME STARTSWITH "P" 
 SELECT distinct EMP_NAME FROM employees_
 WHERE EMP_NAME LIKE "p%";

# SHOW THE NAME OF EMPLOYEE WHOSE NAME ENDSWITH A AND R


# SHOW THE DATA WHOSE NAME ENDSWITH "AR"
SELECT DISTINCT EMP_NAME
FROM EMPLOYEES_
WHERE EMP_NAME LIKE "%AR";

# SHOW THE DATA WHOSE NAME STARTSWITH "N" AND ENDSWITH "A"
SELECT DISTINCT EMP_NAME
FROM EMPLOYEES_
WHERE EMP_NAME LIKE "N%" AND EMP_NAME LIKE "%A";



# SHOW THE DATA WHOSE NAME CONTAIN "T"
SELECT DISTINCT EMP_NAME FROM EMPLOYEES_
WHERE EMP_NAME LIKE "%T%";

SELECT DISTINCT EMP_NAME FROM employees_
WHERE EMP_NAME LIKE "%A%" AND EMP_NAME NOT LIKE "%A,A%";


# CONTAIN R AT 2 ND POSITION
SELECT DISTINCT EMP_NAME FROM employees_
WHERE EMP_NAME LIKE "_R%";


SELECT DISTINCT EMP_NAME FROM employees_
WHERE EMP_NAME LIKE "__R%";


SELECT DISTINCT EMP_NAME FROM employees_
WHERE LENGTH(EMP_NAME)=13;







